# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe04ec6f40f781b34016839d7e512b94d75bd971d8f70f3265a3a25a6052062ad9486556c7e0346f8e401306a3b9c7ab79ba5c4a7e9e8c897a29deac7dae148e

test:
  secret_key_base: ed36bbeb52811fd566f5c5c806a88468d24ab03a4a14bfc69541efcb9a55081cee6260829b75ee00f6e3797333775a65dd5b5c5633236a1282d805a83cb8af16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
